namespace Final_Survivors.Core
{
    public enum Events 
    { 
        IDLE, MOVE, DASH, SHOOT, MELEE, 
        TIME_WARP, TIME_WARP_DAY_TO_NIGHT, TIME_WARP_NIGHT_TO_DAY, INSIDE_FLASHLIGHT, OUTSIDE_FLASHLIGHT,
        TAKE_DAMAGE, RETURN_BULLET, RELOAD, RESET, TBAG, AMMO, 
        SCORE, SPAWNNORMAL, SPAWNELITE, SPAWNBOSS, NORMAL, ELITE, BOSS, NEXTSTAGE,
        PISTOL, MACHINE_GUN, SHOTGUN, SNIPER, SWORD, ROCKET_LAUNCHER
    }
}
